apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ DEPLOY_APP }}
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 1Gi
  accessPolicy:
    outbound:
      external:
        - host: test.salesforce.com
        - host: navdialog--preprod.my.salesforce.com
        - host: navdialog--uat.my.salesforce.com
  envFrom:
    - secret: sf-pdl-kafka
  kafka:
    pool: nav-dev # enum of nav-dev, nav-prod
  env:
    - name: CONTEXT
      value: DEV
    - name: POSTER_SETTINGS # DEFAULT, FROM_BEGINNING, NO_POST, SAMPLE, RUN_ONCE
      value: SAMPLE, FROM_BEGINNING, NO_POST, RUN_ONCE
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: KAFKA_CLIENTID
      value: sf-pdl-kafka
    - name: KAFKA_TOPIC_PERSONDOKUMENT
      value: pdl.pdl-persondokument-tagged-v1
    - name: KAFKA_TOPIC_GEOGRAFISKTILKNYTNING
      value: pdl.geografisktilknytning-v1
    - name: MS_BETWEEN_WORK
      value: '180000'
    - name: SF_TOKENHOST
      value: https://test.salesforce.com
    - name: DEPLOY_APP
      value: {{ DEPLOY_APP }}
    - name: WHITELIST_FILE
      value: '/whitelist/dev.json'