spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: sf-pdl-kafka-prod # Follow name convention <app-name>-<context>
  ingresses:
    - "https://sf-pdl-kafka.intern.nav.no"
  envFrom:
    - secret: sf-pdl-kafka
  env:
    - name: KAFKA_TOPIC
      value: pdl.pdl-persondokument-v1
    - name: WHITELIST_FILE
      value: '/whitelist/prod.json'