apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ DEPLOY_APP }}
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: sf-skjerming-secret
  filesFrom:
    - secret: sf-skjerming-secret
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: POSTER_SETTINGS # DEFAULT, FROM_BEGINNING, NO_POST, SAMPLE, RUN_ONCE, ENCODE_KEY, AVRO_KEY_VALUE, AVRO_VALUE
      value: SAMPLE
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: KAFKA_CLIENTID
      value: sf-skjerming-client-crm
    - name: KAFKA_TOPIC
      value: nom.skjermede-personer-v1
    - name: MS_BETWEEN_WORK
      value: '240000'
    - name: SF_TOKENHOST
      value: https://login.salesforce.com
    - name: SF_VERSION
      value: 'v57.0'
    - name: DEPLOY_APP
      value: {{ DEPLOY_APP }}