spec:
  ingresses:
    - "https://sf-pdl-kafka.intern.nav.no"
  envFrom:
    - secret: kafka-platforce
  env:
    - name: KAFKA_TOPIC
      value: pdl.pdl-persondokument-v1
    - name: WHITELIST_FILE
      value: '/whitelist/prod.json'