apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "{{ DEPLOY_APP }}"
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: sf-pdl-kafka
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: POSTER_FLAGS # DEFAULT, FROM_BEGINNING, SEEK, NO_POST, SAMPLE, RUN_ONCE
      value: SAMPLE, NO_POST, RUN_ONCE, FROM_BEGINNING
    - name: FLAG_SAMPLE
      value: "{{ FLAG_SAMPLE }}"
    - name: FLAG_SEEK
      value: "{{ FLAG_SEEK }}"
    - name: SEEK_OFFSET # Only applied if flag SEEK is set (currently assuming one partition)
      value: "{{ SEEK_OFFSET }}"
    - name: FLAG_NO_POST
      value: "{{ FLAG_NO_POST }}"
    - name: FLAG_RUN_ONCE
      value: "{{ FLAG_RUN_ONCE }}"
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: KAFKA_CLIENT_ID
      value: sf-pdl-kafka
    - name: KAFKA_TOPIC
      value: pdl.geografisktilknytning-v1
    - name: MS_BETWEEN_WORK
      value: '240000'
    - name: SF_TOKENHOST
      value: https://login.salesforce.com
    - name: DEPLOY_APP
      value: "{{ DEPLOY_APP }}"
    - name: WHITELIST_FILE
      value: '/whitelist/prod.json'