spec:
  envFrom:
    - secret: sf-skjerming-prod
  ingresses:
    - "https://sf-skjerming.intern.nav.no"
  env:
    - name: KAFKA_TOPIC
      value: nom.skjermede-personer-v1
    - name: KAFKA_CLIENT_ID
      value: sf-skjerming-client-crm