name: Dispatch

on:
  workflow_dispatch:
    inputs:
      DEPLOY_APP:
        description: 'Deployment Application'
        required: true
        type: choice
        default: 'sf-pdl-kafka'
        options:
          - 'sf-pdl-kafka'
          - 'sf-geografisktilknytning'
      DEPLOY_CLUSTER:
        description: 'Deployment Cluster'
        required: true
        type: choice
        default: 'dev-gcp'
        options:
          - 'dev-gcp'
          - 'prod-gcp'
      FLAG_SEEK:
        description: "Seek"
        required: true
        type: boolean
      SEEK_OFFSET:
        description: "Seek offset"
        required: true
        default: 0
      FLAG_SAMPLE:
        description: "Sample"
        required: true
        type: boolean
      FLAG_NO_POST:
        description: "No post"
        required: true
        type: boolean
      FLAG_RUN_ONCE:
        description: "Run once"
        required: true
        type: boolean
      FLAG_ALT_ID:
        description: "Alt Id"
        required: true
        type: boolean
run-name: >- # Used as run-name on dispatch:
  Dispatch-deploy:
  ${{ inputs.DEPLOY_APP }} - ${{ inputs.DEPLOY_CLUSTER }}
  ${{ inputs.FLAG_SEEK && format(' - SEEK {0}', inputs.SEEK_OFFSET) || '' }}
  ${{ inputs.FLAG_SAMPLE && ' - SAMPLE' || '' }}
  ${{ inputs.FLAG_NO_POST && ' - NO_POST' || '' }}
  ${{ inputs.FLAG_RUN_ONCE && ' - RUN_ONCE' || '' }}
  ${{ inputs.FLAG_ALT_ID && ' - ALT_ID' || '' }}
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.DEPLOY_APP }} to ${{ github.event.inputs.DEPLOY_CLUSTER }} (Dispatched)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Fetch artifact
        id: read-image-url
        run: |
          WORKFLOW_ID=77696646
          ARTIFACT_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/navikt/sf-pdl-kafka/actions/workflows/$WORKFLOW_ID/runs?status=success" | jq -r '.workflow_runs[0].artifacts_url')
          ARTIFACT_DETAILS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $ARTIFACT_URL)
          ARCHIVE_DOWNLOAD_URL=$(echo $ARTIFACT_DETAILS | jq -r '.artifacts[0].archive_download_url')
          curl -s -H "Authorization: token $GITHUB_TOKEN" -o artifact.zip -L $ARCHIVE_DOWNLOAD_URL
          IMAGE_URL=$(unzip -p artifact.zip)
          echo "::set-output name=image_url::$IMAGE_URL"

#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: imageUrl
#          path: ./imageUrl.txt

#      - name: Read image URL from artifact
#        id: read-image-url
#        run: |
#          IMAGE_URL=$(cat ./imageUrl.txt)
#          echo "::set-output name=image_url::$IMAGE_URL"

      - name: Deploy ${{ github.event.inputs.DEPLOY_APP }} to ${{ github.event.inputs.DEPLOY_CLUSTER }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ github.event.inputs.DEPLOY_CLUSTER }}
          RESOURCE: .nais/${{ github.event.inputs.DEPLOY_APP }}/${{ github.event.inputs.DEPLOY_CLUSTER }}.yaml
          VAR: image=${{ steps.read-image-url.outputs.image_url }},DEPLOY_APP=${{ inputs.DEPLOY_APP }},DEPLOY_CLUSTER=${{ inputs.DEPLOY_CLUSTER }},FLAG_SAMPLE=${{ inputs.FLAG_SAMPLE }},FLAG_SEEK=${{ inputs.FLAG_SEEK }},SEEK_OFFSET=${{ inputs.SEEK_OFFSET }},FLAG_NO_POST=${{ inputs.FLAG_NO_POST }},FLAG_RUN_ONCE=${{ inputs.FLAG_RUN_ONCE }},FLAG_ALT_ID=${{ inputs.FLAG_ALT_ID }}