name: Run workflow from github

on: [workflow_dispatch]

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    inputs: # Define inputs for manual triggering
      DEPLOY_APP:
        description: 'Deployment Application'
        required: true
        default: 'sf-pdl-kafka'
      DEPLOY_CLUSTER:
        description: 'Deployment Cluster'
        required: true
        default: 'dev-gcp'
    secrets: inherit
    with:
      DEPLOY_APP: ${{ github.event.inputs.DEPLOY_APP }}
      DEPLOY_CLUSTER: ${{ github.event.inputs.DEPLOY_CLUSTER }}