name: Preconfigured run on push

on: [pull_request] #[push, pull_request]

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-pdl-kafka # sf-geografisktilknytning
      DEPLOY_CLUSTER: dev-gcp
      FLAG_SAMPLE: true