name: Preconfigured run on push

on: [push, pull_request]

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-pdl-kafka # sf-pdl-kafka # sf-geografisktilknytning
      DEPLOY_CLUSTER: prod-gcp

      # Start consuming from a particular offset
      # Note that the consumer will go there each time the pod reboots, so make sure you turn this off once done
      FLAG_SEEK: false

      # Where to go if flag seek is set. Will seek to next offset that exists on queue, i.e '0' equals 'from beginning'
      SEEK_OFFSET: '-1' # '20777320'- start here to save some time for test case sf-pdl-kafka

      # How many samples should be stored. Will sample first ones that passes filter.
      NUMBER_OF_SAMPLES: '5'

      # To not post any records to salesforce - dry run
      FLAG_NO_POST: true

      # To add -alt postfix to client id - will look like an alter ego to kafka cluster. Useful for doing an operation
      # and then switching off to return to previous position.
      FLAG_ALT_ID: false
