name: Preconfigured run on push

on: [push, pull_request] #[push, pull_request]

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-pdl-kafka # sf-geografisktilknytning
      DEPLOY_CLUSTER: dev-gcp
      FLAG_SEEK: true
      SEEK_OFFSET: '20777320' # - save some time for test case
      NUMBER_OF_SAMPLES: '5'
      FLAG_NO_POST: true
      FLAG_RUN_ONCE: true
      FLAG_ALT_ID: false